# Generated by Django 5.0.1 on 2024-02-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locum', '0001_initial'),
        ('address', '0002_address_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
