# Generated by Django 5.0.1 on 2024-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locum', '0003_locumlanguages'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Locum.locumlanguages'),
        ),
    ]
