# Generated by Django 5.0.1 on 2024-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locum', '0004_locum_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locum',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='locum',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
