# Generated by Django 5.0.1 on 2024-02-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locum', '0006_locumaffiliations_locumspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocumEducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('locum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locum.locum')),
            ],
        ),
    ]
