# Generated by Django 5.0.1 on 2024-04-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locum', '0007_locumeducationalbackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locum',
            name='website',
        ),
    ]
