# Generated by Django 5.0.1 on 2024-02-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Admin', 'Admin'), ('Patient', 'Patient'), ('Locum', 'Locum'), ('Practice', 'Practice')], max_length=25, null=True),
        ),
    ]
