# Generated by Django 5.0.1 on 2024-03-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Admin', 'Admin'), ('Patient', 'Patient'), ('Locum', 'Locum'), ('Practice', 'Practice')], help_text='Account type', max_length=25, null=True),
        ),
    ]
