# Generated by Django 5.0.1 on 2024-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practiceservices_practice_accepted_insurances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='services',
        ),
        migrations.AddField(
            model_name='practice',
            name='services',
            field=models.ManyToManyField(to='practice.practiceservices'),
        ),
    ]
