# Generated by Django 5.0.1 on 2024-03-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.BooleanField(default=False)),
                ('wheel_chair_accessible_parking', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('infotainment', models.BooleanField(default=False)),
                ('pricing', models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Expensive', 'Expensive')], max_length=10)),
                ('insurance', models.CharField(choices=[('Yes', 'Yes'), ('Cash', 'Cash')], max_length=10)),
                ('languages', models.ManyToManyField(to='address.languages')),
            ],
        ),
    ]
