# Generated by Django 5.0.1 on 2024-03-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_languages_accessibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
