# Generated by Django 5.0.1 on 2024-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_days_remove_appointmentsavailability_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages',
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='Doctor.doctorlanguages'),
        ),
    ]
