# Generated by Django 5.0.1 on 2024-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctorlanguages_remove_doctor_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlanguages',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorlanguages',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
