# Generated by Django 5.0.1 on 2024-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_doctor_user_alter_appointmentsavailability_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorspecialization',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
