# Generated by Django 5.0.1 on 2024-02-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
