# Generated by Django 5.0.1 on 2024-02-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_remove_doctor_email_remove_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
