# Generated by Django 5.0.1 on 2024-02-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpracticelocationinfo',
            name='address',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.address'),
        ),
    ]
