# Generated by Django 5.0.1 on 2024-02-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_alter_doctorpracticelocationinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorexperience',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorexperience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctorpracticelocationinfo'),
        ),
    ]
