# Generated by Django 5.0.1 on 2024-02-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_remove_doctorexperience_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorexperience',
            name='location',
        ),
        migrations.AddField(
            model_name='doctorexperience',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
    ]
