# Generated by Django 5.0.1 on 2024-02-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_remove_doctorexperience_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='doctor',
        ),
    ]
