# Generated by Django 5.0.1 on 2024-02-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_remove_address_doctor'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpracticelocationinfo',
            name='address',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.RenameField(
            model_name='doctorpracticelocationinfo',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
