# Generated by Django 5.0.1 on 2024-02-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_alter_doctorpracticelocationinfo_address_and_more'),
        ('address', '0002_address_suburb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='home_address',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
