# Generated by Django 5.0.1 on 2024-03-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_remove_doctor_home_address_doctor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreviews',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
