# Generated by Django 5.0.1 on 2024-03-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_rename_date_create_doctorreviews_date_created'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsLocum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, max_length=20, null=True)),
                ('date_to', models.DateField(blank=True, max_length=10, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
        ),
    ]
