# Generated by Django 5.0.1 on 2024-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_doctorslocum'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslocum',
            name='is_active',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
