# Generated by Django 5.0.1 on 2024-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0019_doctorslocum_is_active'),
        ('address', '0003_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.AlterField(
            model_name='doctorpracticelocationinfo',
            name='accepted_insurances',
            field=models.ManyToManyField(to='address.insurance'),
        ),
    ]
