# Generated by Django 5.0.1 on 2024-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_alter_doctor_languages'),
        ('address', '0007_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='doctorpracticelocationinfo',
            name='services',
            field=models.ManyToManyField(to='address.services'),
        ),
    ]
