# Generated by Django 5.0.1 on 2024-04-13 21:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_delete_services_and_more'),
        ('address', '0007_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlanguages',
            name='language',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.languages'),
        ),
        migrations.AlterField(
            model_name='doctorlanguages',
            name='proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='DoctorPracticeLocationInfo',
        ),
    ]
